import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { HealthFormData, HealthResults } from '@/types/health';

export function generateHealthReport(formData: HealthFormData, results: HealthResults): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // Header
  doc.setFillColor(13, 148, 136); // Primary teal
  doc.rect(0, 0, pageWidth, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('Biological Age Report', 20, 25);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Generated on ${new Date().toLocaleDateString()}`, 20, 35);

  // Reset text color
  doc.setTextColor(0, 0, 0);

  // Summary section
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('Health Summary', 20, 55);

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  
  const summaryData = [
    ['Chronological Age', `${formData.chronologicalAge} years`],
    ['Biological Age', `${results.biologicalAge} years`],
    ['Age Difference', `${results.ageDifference > 0 ? '+' : ''}${results.ageDifference} years`],
    ['Health Score', `${results.healthScore}/10`],
    ['Risk Zone', results.riskZone.toUpperCase()],
  ];

  autoTable(doc, {
    startY: 60,
    head: [['Metric', 'Value']],
    body: summaryData,
    theme: 'striped',
    headStyles: { fillColor: [13, 148, 136] },
    styles: { fontSize: 11 },
  });

  // Input data section
  let yPos = (doc as any).lastAutoTable.finalY + 15;
  
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('Your Health Data', 20, yPos);

  const inputData = [
    ['Gender', formData.gender],
    ['Sleep Hours', `${formData.sleepHours} hours`],
    ['Sleep Quality', formData.sleepQuality],
    ['Daily Steps', formData.dailySteps.toLocaleString()],
    ['Water Intake', `${formData.waterIntake}L`],
    ['Smoker', formData.smoker ? 'Yes' : 'No'],
    ['Alcohol Frequency', formData.alcoholFrequency],
    ['Exercise Frequency', formData.exerciseFrequency],
    ['BMI', formData.bmi.toString()],
    ['Resting Heart Rate', `${formData.restingHeartRate} bpm`],
    ['Blood Pressure', `${formData.systolicBP}/${formData.diastolicBP} mmHg`],
    ['Total Cholesterol', `${formData.cholesterolTotal} mg/dL`],
    ['Fasting Blood Sugar', `${formData.bloodSugar} mg/dL`],
  ];

  autoTable(doc, {
    startY: yPos + 5,
    head: [['Parameter', 'Value']],
    body: inputData,
    theme: 'striped',
    headStyles: { fillColor: [13, 148, 136] },
    styles: { fontSize: 10 },
  });

  // Metrics analysis
  yPos = (doc as any).lastAutoTable.finalY + 15;
  
  if (yPos > 230) {
    doc.addPage();
    yPos = 20;
  }

  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('Metrics Analysis', 20, yPos);

  const metricsData = results.metrics.map(m => [
    m.name,
    m.value.toString(),
    m.optimal,
    m.status.toUpperCase(),
  ]);

  autoTable(doc, {
    startY: yPos + 5,
    head: [['Metric', 'Your Value', 'Optimal Range', 'Status']],
    body: metricsData,
    theme: 'striped',
    headStyles: { fillColor: [13, 148, 136] },
    styles: { fontSize: 10 },
    columnStyles: {
      3: {
        cellWidth: 30,
        halign: 'center',
      },
    },
  });

  // Recommendations
  if (results.recommendations.length > 0) {
    yPos = (doc as any).lastAutoTable.finalY + 15;
    
    if (yPos > 220) {
      doc.addPage();
      yPos = 20;
    }

    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text('Personalized Recommendations', 20, yPos);

    const recsData = results.recommendations.map((r, i) => [
      (i + 1).toString(),
      r.title,
      r.description,
      r.impact.toUpperCase(),
    ]);

    autoTable(doc, {
      startY: yPos + 5,
      head: [['#', 'Recommendation', 'Description', 'Impact']],
      body: recsData,
      theme: 'striped',
      headStyles: { fillColor: [13, 148, 136] },
      styles: { fontSize: 9 },
      columnStyles: {
        0: { cellWidth: 10 },
        1: { cellWidth: 40 },
        2: { cellWidth: 100 },
        3: { cellWidth: 20, halign: 'center' },
      },
    });
  }

  // Disclaimer
  doc.addPage();
  
  doc.setFillColor(245, 245, 245);
  doc.rect(15, 15, pageWidth - 30, 80, 'F');
  
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Important Disclaimer', 20, 30);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  const disclaimer = `This report is generated by an AI-powered health assessment tool and is intended for informational purposes only. It should not be considered as medical advice, diagnosis, or treatment recommendations.

The biological age calculation is based on statistical models and the self-reported data you provided. Results may not reflect your actual physiological state.

Key points to remember:
• Always consult with qualified healthcare professionals before making any health decisions
• This assessment does not replace regular medical check-ups
• Individual health needs vary; what works for others may not work for you
• Data privacy: Your health information is not stored permanently

For accurate health assessment, please consult with your physician or healthcare provider who can perform proper clinical evaluations.`;

  const lines = doc.splitTextToSize(disclaimer, pageWidth - 45);
  doc.text(lines, 20, 42);

  // Footer on all pages
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text(
      'Biological Age & Longevity Intelligence System',
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    );
    doc.text(
      `Page ${i} of ${pageCount}`,
      pageWidth - 20,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'right' }
    );
  }

  // Save the PDF
  doc.save('health-report.pdf');
}
